project:
  type: website
  output-dir: docs
  execute-dir: project


website:
  title: 'ZULE Lab Resources'
  page-navigation: true
  reader-mode: false
  repo-url: https://github.com/zule-lab/internal-resources
  repo-actions: [edit]
  sidebar:
    style: "docked"
    logo: imgs/ZULE_logo_white.png
    search: true
    contents:
      - href: index.qmd
        text: Home
      - section: "Lab Policies"
        href: policies/00-policies.qmd
        contents:
          - href: policies/01-code-of-conduct.qmd
            text: Lab Code of Conduct
          - href: policies/02-individual-mentoring-plan.qmd
            text: Individual Mentoring Plan
          - href: policies/04-summer-undergrad-orientation.qmd
            text: Summer Undergraduate Student Orientation
          - href: policies/05-international-student-orientation.qmd
            text: Guide for Incoming International Students
          - href: policies/06-data-management.qmd
            text: Data Management & Archiving Policy
      - section: "Data Resources"
        href: spatial-resources/00-spatial-resources.qmd
        contents:
          - href: spatial-resources/01-montreal-data.qmd
            text: Montreal Data
          - href: spatial-resources/02-quebec-data.qmd
            text: Quebec Data
          - href: spatial-resources/03-canada-data.qmd
            text: Canada Data
          - href: spatial-resources/04-other.qmd
            text: Other Spatial Resources
      - section: "Other Resources"
        href: other-resources/00-other-resources.qmd
        contents:
          - href: other-resources/01-zule-lab-reading-list.qmd
            text: ZULE Lab Reading List
      - section: Templates
        href:
        contents:
           - text: MSc Proposal Outline (pdf)
             href: policies/msc-proposal-outline.pdf



format:
  html:
    grid:
      sidebar-width: 350px
      margin-width: 200px
    theme:
      light: flatly
      dark: darkly
    toc: true
